#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/38.js
# Generated at: 2026-09-08T21:04:52Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/38.js

cat << 'NODEOUTPUT'
10
7
NODEOUTPUT

exit 0
