#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/39.js
# Generated at: 2026-09-08T21:05:46Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/39.js

cat << 'NODEOUTPUT'
19
5
6
8
NODEOUTPUT

exit 0
