#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/40.js
# Generated at: 2026-09-10T02:27:41Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/.terminals/_dev_pts_1/dev_1/._/._/._/tests/basics/40.js

cat << 'NODEOUTPUT'
33
31
56
465
520
1137
415
23998
NODEOUTPUT

exit 0
